version: "3.7"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: kodersky/golang-api-example
    container_name: golang-api-example
    restart: on-failure
    tty: true
    environment:
      SERVICE_NAME: golang
      SERVICE_TAGS: dev
      TERM: xterm-256color
      TZ: Asia/Bangkok
    ports:
      - 8081:8081
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: golang-example-api-db
    restart: unless-stopped
    tty: true
    ports:
        - "33306:3306"
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: orders
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
      TZ: Asia/Bangkok
    volumes:
      - orders-db:/var/lib/mysql
volumes:
  orders-db: