// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	maps "googlemaps.github.io/maps"
)

// GoogleMapClient is an autogenerated mock type for the GoogleMapClient type
type GoogleMapClient struct {
	mock.Mock
}

// DistanceMatrix provides a mock function with given fields: ctx, r
func (_m *GoogleMapClient) DistanceMatrix(ctx context.Context, r *maps.DistanceMatrixRequest) (*maps.DistanceMatrixResponse, error) {
	ret := _m.Called(ctx, r)

	var r0 *maps.DistanceMatrixResponse
	if rf, ok := ret.Get(0).(func(context.Context, *maps.DistanceMatrixRequest) *maps.DistanceMatrixResponse); ok {
		r0 = rf(ctx, r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*maps.DistanceMatrixResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *maps.DistanceMatrixRequest) error); ok {
		r1 = rf(ctx, r)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
